import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { bsc, bscTestnet } from "@reown/appkit/networks";
import type { Chain } from "viem";
import { cookieStorage, createStorage } from "wagmi";

// Read Project ID from environment variables
export const projectId =
  (process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID as string | undefined) ||
  "demo-project-id";

// Warn if using demo project ID
if (projectId === "demo-project-id") {
  console.warn(
    "Using demo project ID. Please set NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID in your .env file for production use."
  );
}

// Define supported networks, explicitly typed as a non-empty array of Chains
export const networks: [Chain, ...Chain[]] = [bsc, bscTestnet];

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }), // Use cookieStorage for SSR
  ssr: true, // Enable SSR support
  projectId,
  networks, // Pass the explicitly typed networks array
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
