"""add_data_column_to_hedge_fund_flows

Revision ID: 0002
Revises: 0001
Create Date: 2025-06-22 17:30:50.992184

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: list[str] | None = None
depends_on: list[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hedge_fund_flows", sa.Column("data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hedge_fund_flows", "data")
    # ### end Alembic commands ###
